FROM python:3.12.7-slim

ARG POETRY_VERSION=1.8.3
RUN apt-get update && apt-get install -y --no-install-recommends wget nano
RUN useradd -m -d /home/user -s /bin/bash user && adduser user sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER user

RUN pip install --upgrade pip && \
    pip install "poetry==${POETRY_VERSION}" && \
    python -m poetry config virtualenvs.create true

WORKDIR /workspaces/fast_api_cource
COPY pyproject.toml poetry.lock ./ 

# Установить зависимости из всех групп
RUN python -m poetry install --no-interaction --no-ansi --no-cache -vvv